install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_success:
  - bash ci/after_success.sh

branches:
  only:
    - staging
    - trying

notifications:
  email:
    on_success: never
